package com.cognizant.aws.fse.userservice.Json.Domain;

import java.util.Random;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerator;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBKeyed;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.util.StringUtils;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
@JsonIgnoreProperties(ignoreUnknown =  true)
@DynamoDBTable(tableName = "FSEProfile")
public class UserJsonModel {
	@JsonProperty("UserId")
	String userId;
	@JsonProperty("AssociateName")
	String associateName;
	@JsonProperty("AssociateId")
	String associateId;
	@JsonProperty("Mobile")
	String mobile;
	@JsonProperty("Email")
	String email;
	@JsonProperty("Skill")
	String skill;
	@JsonProperty("SkillLevel")
	int skillLevel;
	@JsonProperty("SkillType")
	String skillType;
	

	public UserJsonModel() {

	}
	/*public User(String 
			String argName,String argAssociateId,String argMobile,String argEmail) {
		this.name = argName;
		this.associateId=argAssociateId;
		this.email=argEmail;
		this.mobile=argMobile;
	}*/

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "GSI-search-index1")
	@DynamoDBRangeKey(attributeName ="AssociateId")	
	public String getAssociateName() {
		return associateName;
	}
	public void setAssociateName(String assoicateName) {
		this.associateName = assoicateName;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "GSI-search-index2")
	
	@DynamoDBHashKey(attributeName ="AssociateName")
	public String getAssociateId() {
		return associateId;
	}
	public void setAssociateId(String associateId) {
		this.associateId = associateId;
	}
	
	@DynamoDBAttribute(attributeName="Mobile")
	public String getMobile() {
		return mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	@DynamoDBAttribute(attributeName = "Email")
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "User [associateName=" + associateName + ", associateId=" + associateId + ", mobile=" + mobile + ", email=" + email
				+ ", skill=" + skill + ", skillLevel=" + skillLevel + ", skillType=" + skillType + "]";
	}
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "GSI-search-index3")
	@DynamoDBAttribute(attributeName="Skill")
	public String getSkill() {
		return skill;
	}
	
	public void setSkill(String skill) {
		this.skill = skill;
	}
	
	@DynamoDBAttribute(attributeName ="SkillLevel")
	public int getSkillLevel() {
		return skillLevel;
	}
	public void setSkillLevel(int skillLevel) {
		this.skillLevel = skillLevel;
	}
	
	@DynamoDBAttribute(attributeName="SkillType")
	public String getSkillType() {
		return skillType;
	}
	public void setSkillType(String skillType) {
		this.skillType = skillType;
	}
	
	@DynamoDBAutoGenerated(generator = DynamoDBAutoGenerator.class)
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	

}
